// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered assistant to improve appraisal text.
 *
 * - improveAppraisalText - A function that improves the appraisal text.
 * - ImproveAppraisalTextInput - The input type for the improveAppraisalText function.
 * - ImproveAppraisalTextOutput - The return type for the improveAppraisalText function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ImproveAppraisalTextInputSchema = z.object({
  appraisalText: z.string().describe('The appraisal text to improve.'),
});
export type ImproveAppraisalTextInput = z.infer<typeof ImproveAppraisalTextInputSchema>;

const ImproveAppraisalTextOutputSchema = z.object({
  improvedAppraisalText: z.string().describe('The improved appraisal text.'),
});
export type ImproveAppraisalTextOutput = z.infer<typeof ImproveAppraisalTextOutputSchema>;

export async function improveAppraisalText(
  input: ImproveAppraisalTextInput
): Promise<ImproveAppraisalTextOutput> {
  return improveAppraisalTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveAppraisalTextPrompt',
  input: {
    schema: z.object({
      appraisalText: z.string().describe('The appraisal text to improve.'),
    }),
  },
  output: {
    schema: z.object({
      improvedAppraisalText: z.string().describe('The improved appraisal text.'),
    }),
  },
  prompt: `You are an AI-powered assistant designed to improve appraisal text.
      Please review the following appraisal text and suggest improvements to make it more constructive and impactful.

      Appraisal Text: {{{appraisalText}}}

      Improved Appraisal Text:`,
});

const improveAppraisalTextFlow = ai.defineFlow<
  typeof ImproveAppraisalTextInputSchema,
  typeof ImproveAppraisalTextOutputSchema
>(
  {
    name: 'improveAppraisalTextFlow',
    inputSchema: ImproveAppraisalTextInputSchema,
    outputSchema: ImproveAppraisalTextOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return {
      improvedAppraisalText: output!.improvedAppraisalText,
    };
  }
);
